name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: production

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2

    - name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker images
      run: |
        docker-compose build --build-arg API_URL="https://www.gabrielmarreiros.com.br/inventory-management/api" --no-cache
        docker push gabrielmarreiros/inventory-management-angular-java-backend:latest
        docker push gabrielmarreiros/inventory-management-angular-java-frontend:latest

    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_IP }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_PASSWORD }}
        script: |
          cd /root/docker_composes/inventory-management-angular-java
          docker-compose rm -s -f
          docker rmi gabrielmarreiros/inventory-management-angular-java-backend
          docker rmi gabrielmarreiros/inventory-management-angular-java-frontend
          docker-compose up -d
